// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDdUJedRzvzxJNjN5cQB_C-qBqCEjoKfU',
    appId: '1:183591499676:web:6beee013ac2510e7313a59',
    messagingSenderId: '183591499676',
    projectId: 'delizio-eedc1',
    authDomain: 'delizio-eedc1.firebaseapp.com',
    storageBucket: 'delizio-eedc1.firebasestorage.app',
    measurementId: 'G-VBPCL23YWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpqAFDbpaO04UBRgpmDTESmSkxBTT7EAc',
    appId: '1:183591499676:android:0f71e39a227c5336313a59',
    messagingSenderId: '183591499676',
    projectId: 'delizio-eedc1',
    storageBucket: 'delizio-eedc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe6TuRx2yuyN1tvv27A_6l5mXdL2ozdiQ',
    appId: '1:183591499676:ios:4c79bc4dbf03ee94313a59',
    messagingSenderId: '183591499676',
    projectId: 'delizio-eedc1',
    storageBucket: 'delizio-eedc1.firebasestorage.app',
    iosBundleId: 'com.example.delizioParaRestaurantes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe6TuRx2yuyN1tvv27A_6l5mXdL2ozdiQ',
    appId: '1:183591499676:ios:4c79bc4dbf03ee94313a59',
    messagingSenderId: '183591499676',
    projectId: 'delizio-eedc1',
    storageBucket: 'delizio-eedc1.firebasestorage.app',
    iosBundleId: 'com.example.delizioParaRestaurantes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDdUJedRzvzxJNjN5cQB_C-qBqCEjoKfU',
    appId: '1:183591499676:web:efa19b49961b3e27313a59',
    messagingSenderId: '183591499676',
    projectId: 'delizio-eedc1',
    authDomain: 'delizio-eedc1.firebaseapp.com',
    storageBucket: 'delizio-eedc1.firebasestorage.app',
    measurementId: 'G-0G8J3W4XYM',
  );
}
